---
- name: Include deploy for Debian systems
  include: http_debian.yaml
  when: ansible_os_family == 'Debian'

- name: Include deploy for RedHat systems
  include: http_RedHat.yaml
  when: ansible_os_family == 'RedHat'

- name: Remove Index file for Debian
  file:
    path: "{{ default_home_debian  }}/index.html"
    state: absent
  when: ansible_os_family == 'Debian'

- name: Copy first page for Debian
  copy:
    src: index.html
    dest: "{{ default_home_debian  }}"
  when: ansible_os_family == 'Debian'
  notify:
    - restart nginx

- name: Remove Index file for RedHat
  file:
    path: "{{ default_home_redhat  }}/index.html"
    state: absent
  when: ansible_os_family == 'RedHat'

- name: Copy first page for RedHat
  copy:
    src: index.html
    dest: "{{ default_home_redhat  }}"
  when: ansible_os_family == 'RedHat'
  notify:
    - restart nginx


- meta: flush_handlers

- name: Check file
  shell: |
    cat /etc/os-release | egrep "^NAME" | cut -d'"' -f 2
  register: out
  notify:
    - print out

- meta: flush_handlers

- name: Check connection to localhost
  wait_for:
    host: "localhost"
    port: "80"
    state: started
    timeout: 3
  register: out

- name: Check content to sites
  uri:
    url: http://localhost
    return_content: yes
  register: out
  failed_when: "'comrades' not in out.content"

#- debug:
#    msg: "{{  out  }}"

- name: Templates
  template:
    src: "hosts.j2"
    dest: "/etc/hosts"
    backup: yes

- name: Check content to sites
  uri:
    url: "http://{{ item.name }}"
    return_content: yes
  loop: "{{ virtual_hosts }}"

