---
- name: restart apache
  service:
    name: "{{  'apache2' if (ansible_os_family == 'Debian') else 'httpd' }}"
    state: restarted
    enabled: yes

- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: print out
  debug:
    msg: "{{ out.stdout  }}"
